### ISSUE TITLE
Drones do not spawn

### ISSUE THREAD

**Issue by lpmrz** [ctu-mrs/uvdar_core#6]
Hello,

When I start beacon.sh, drones fail to spawn. It looks as below;

![Screenshot from 2021-08-26 12-37-54](https://user-images.githubusercontent.com/18270807/130940021-0dfce580-abba-423b-a42c-ba730ee2e068.png)

**Comment by ViktorWalter** [comment]
This is being addressed in [here](https://github.com/ctu-mrs/uvdar_gazebo_plugin/issues/8)
